[package]
name = "screenmanual-store"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
screenmanual-core = { path = "../core" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
imageproc = { version = "0.25", default-features = false }
